language: node_js
os:
- linux
- osx
node_js:
- 4
- 5
- 6
notifications:
  email: false
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/54f8a1e753f859f5ca1a
    on_start: never
    on_failure: change
deploy:
  provider: npm
  email: jimmy.aumard@gmail.com
  api_key:
    secure: kvq1cpuZis4sU/QDD/y3fhDoeNRGJEtZS1xneet/nP2xfT4zHDhpQqO9u2EfHTLYkA0GzTWcRSlZYptZzhFzm1qqYBuyccoahDtXsGdMu1tRGJDS+esJ01NPu3djZwroqlNkjc0Khmaf1ERX8evSdJ3WiLsJmk65d4EgsJa9RwC8iplSrqmLJoH0oNDJFdn33cjPHW+gzNO5EU84i0SAatePTFJrGOyk/sVSzL2FuL3Fc57XFMPYN7wut6c8gLDD0UdQdkhxtW6WMnKMUi+ePBm7sBV1c9rWN9ULUjVThnUjAFQFjY5FJcPYe7vat8GAS1kolecmf/K6Z4D1naQiNmUPpW3KyuG3viiuZ04cM4tQ5Cp/2RE+TMJXVRx1eMIJ+zF/9HxlWw+tSsBX9/MVWpfBKzBZWDV2WHuLjh6ccWQ1jRq0q9fKpLRvj9fxMpnXgtEN16P9+FjezxAX8k1TagPTnEm4JEN7R2BpF3oE8ewXVdieoK+KSrix7R7oKojgm9OkFHeT+Z3mtZcUZfKBc3JfU56FmURoo24vOMNviVsX7Q0afHhHmDQnl0h8gJMposEAWLouO3fw/zYnJm5plymGsKfXoDjYS7Idj5w+KGwYCVJTrYzKy75fG0It/KKMUx/AcoAGxUEgsVCeYhWmpznVhC67vEuicBcHv+nrzXA=
  on:
    tags: true
    repo: jaumard/trailpack-twilio
    node: 6
